default_platform(:android)

platform :android do

  desc "Deploy a new version to Google Play (internal track)"
  lane :deploy_internal do
    upload_to_play_store(
      track:            "internal",
      aab:              "app/build/outputs/bundle/release/app-release.aab",
      metadata_path:    "fastlane/metadata/android",
      skip_upload_apk:  true,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Promote internal → production"
  lane :promote_to_production do
    upload_to_play_store(
      track:           "internal",
      track_promote_to: "production"
    )
  end

end
